/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/quarry_rocks.glb --transform 
Files: public/models/quarry_rocks.glb [18.51MB] > C:\Users\tibog\Documents\VSCODE\wawa-game\quarry_rocks-transformed.glb [2.99MB] (84%)
Author: Studio Lab (https://sketchfab.com/studiolab.dev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/quarry-rocks-e3649a3cfb1247afa8f097d3603f27fe
Title: Quarry Rocks
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/quarry_rocks-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.QuarryRock01_QuarryRock01Shader_0.geometry} material={materials.QuarryRock01Shader} scale={0.01} />
      <mesh geometry={nodes.QuarryRock02_QuarryRock02Shader_0.geometry} material={materials.QuarryRock02Shader} position={[-5, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.QuarryRock03_QuarryRock03Shader_0.geometry} material={materials.QuarryRock03Shader} position={[-11, -1.361, 0]} scale={0.01} />
      <mesh geometry={nodes.QuarryRock04_QuarryRock04Shader_0.geometry} material={materials.QuarryRock04Shader} position={[6, -1.232, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/quarry_rocks-transformed.glb')
